
version: 2

models:
    - name: Diabetes
      description: "Sample Table"
      columns:
          - name: id
            description: "The primary key for this table"
           ## tests:
             ###   - unique
              ###  - not_null


