version: 2

models:

  - name: dim_customers
    description: "Retail customer dimension"
    columns: 
      - name: CustomerKey 
        description: "The Primary key for Customers"
        tests: 
            - unique
            - not_null
            
        


